- name: Deploy to EC2
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      whoami
      cd /home/ubuntu/finapp
      git pull origin main
      npm install
      pm2 restart finapp
      echo "Deployed successfully"
